name: Build and Deploy
on: 
  workflow_dispatch
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t myapp:latest .
      
      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZ_CREDENTIALS}}
      - name: Push to ACR
        run: |
          az acr login -n sslablabacrels
          docker tag myapp:latest sslablabacrels.azurecr.io/myapp:latest
          docker push sslablabacrels.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: sslab-webappels
          images: sslablabacrels.azurecr.io/myapp:latest
